---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: geerlingguy/docker-debian13-ansible:latest
    pre_build_image: true
    privileged: true
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
